/*
  Sketch generated by the Arduino IoT Cloud Thing "Arm"

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int indiceDeg;
  int palmoDeg;
  int polliceDeg;
  int polsoDeg;
  int treDitaDeg;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.

  The rest is coded by @NexIsDumb.
*/

#include <Servo.h>
#include "arduino_secrets.h"
#include "thingProperties.h"

Servo Pollice;      //1
Servo Palmo;        //2
Servo Polso;        //3
Servo Indice;       //4
Servo TreDita;      //5

const int PinPollice = 8;  // Digital thumb pin connected to servo                1
const int PinPalmo = 9;  // Digital palm pin connected to servo                   2
const int PinPolso = 10;  // Digital wrist pin connected to servo                 3
const int PinIndice = 11;  // Digital index pin connected to servo                4
const int PinTreDita = 12;  // Digital conjoined-fingers pin connected to servo   5

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
    The following function allows you to obtain more information
    related to the state of network and IoT Cloud connection and errors
    the higher number the more granular information you’ll get.
    The default is 0 (only errors).
    Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  // Servos' pins configuration
  Pollice.attach(PinPollice);         //1
  Palmo.attach(PinPalmo);             //2
  Polso.attach(PinPolso);             //3
  Indice.attach(PinIndice);           //4
  TreDita.attach(PinTreDita);         //5
}

void loop() {
  ArduinoCloud.update();
}

/*
  Since IndiceDeg is READ_WRITE variable, onIndiceDegChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onIndiceDegChange()  {
  Indice.write(indiceDeg);
}

/*
  Since PalmoDeg is READ_WRITE variable, onPalmoDegChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPalmoDegChange()  {
  Palmo.write(palmoDeg);
}

/*
  Since PolliceDeg is READ_WRITE variable, onPolliceDegChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPolliceDegChange()  {
  Pollice.write(polliceDeg);
}

/*
  Since PolsoDeg is READ_WRITE variable, onPolsoDegChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPolsoDegChange()  {
  Polso.write(polsoDeg);
}

/*
  Since TreDitaDeg is READ_WRITE variable, onTreDitaDegChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTreDitaDegChange()  {
  TreDita.write(treDitaDeg);
}