// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onIndiceDegChange();
void onPalmoDegChange();
void onPolliceDegChange();
void onPolsoDegChange();
void onTreDitaDegChange();

// THESE must be synced with the variables in the Arduino IoT Cloud "Glove" Thing; use the Thing dashboard on Arduino Cloud  - Nex
int indiceDeg;
int palmoDeg;
int polliceDeg;
int polsoDeg;
int treDitaDeg;

void initProperties() {
  ArduinoCloud.addProperty(indiceDeg, READWRITE, ON_CHANGE, onIndiceDegChange);
  ArduinoCloud.addProperty(palmoDeg, READWRITE, ON_CHANGE, onPalmoDegChange);
  ArduinoCloud.addProperty(polliceDeg, READWRITE, ON_CHANGE, onPolliceDegChange);
  ArduinoCloud.addProperty(polsoDeg, READWRITE, ON_CHANGE, onPolsoDegChange);
  ArduinoCloud.addProperty(treDitaDeg, READWRITE, ON_CHANGE, onTreDitaDegChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);