// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

// THESE must be synced with the variables in the Arduino IoT Cloud "Arm" Thing; use the Thing dashboard on Arduino Cloud  - Nex
int indiceDeg;
int palmoDeg;
int polliceDeg;
int polsoDeg;
int treDitaDeg;

void initProperties() {
  ArduinoCloud.addProperty(indiceDeg, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(palmoDeg, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(polliceDeg, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(polsoDeg, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(treDitaDeg, READ, ON_CHANGE, NULL);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);