#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Glove for Rover"

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int indexVal;
  int threeFingVal;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.

  The rest is coded by @NexIsDumb, @Matte549.
*/

#include "arduino_secrets.h"
#include "thingProperties.h"

// Potentiometer pins
const int potPinIndex = A4;  // Analogic index pin connected to the potentiometer                   1
const int potPinThreeFing = A5;  // Analogic conjoined-fingers pin connected to the potentiometer   2

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
    The following function allows you to obtain more information
    related to the state of network and IoT Cloud connection and errors
    the higher number the more granular information you’ll get.
    The default is 0 (only errors).
    Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();

  /*
    Mapping the potentiometer sensors value to the servo range and adapting the potentiometer min and max values.
    From 0 to 1023 => The raw potentiometer rotation value.

    NOTE: The Barcellona Rover wants values between -1 and 1 for each movement,
    but due to arduino's way of handling floats, its better if we send them between -100 and 100
    while the Rover's input handler is gonna actually /100 them to transform the values correctly.
  */
  indexVal = map(analogRead(potPinIndex), 0, 1023, 100, -100);  //         1
  threeFingVal = map(analogRead(potPinThreeFing), 0, 1023, 100, -100); //  2
}